### PR TITLE
Fix bug in resign logic

### PR DESCRIPTION
**Pull request by ujh**
The bot lost against Brown (random player) as it resigned when all
simulated moves lead to a loss. At the end of the game this can however
happen when the only possible moves are plays in the opponents eyes.

So now we only resign if both all simulations lead to a loss and playing
a pass move would lead to a loss.

### CODE REVIEW

**Comment by TisButMe** [comment]
It looks like the build is failing because its using an older version of regex, but it looks fixed in the last master. Manually triggering a re-build should make the error go away.

**Comment by ujh** [comment]
Actually, I think my fix is wrong. :) I'll investigate further later. I believe it's a but in the `AmafEngine` code.

**Comment by ujh** [comment]
OK, here's the real fix. It turns out that the `AmafEngine` didn't even record if the first move in a playout (i.e. the one selected to be simulated by the engine) was a win or a loss. It's no wonder that the results were bad! Or rather, it's a testament to the (comparative) strength of the AMAF heuristic that this was even stronger than pure Monte Carlo.

**Comment by ujh** [comment]
And I'm done I think. The actual playing of the random games is now in the constructor of `Playout` as it always seemed weird that you had to call `new` and then `run`.

Please have a look again @TisButMe and @iopq.

**Comment by TisButMe** [comment]
Looks fine, but I wonder if keeping the name Playout::new instead of Playout::run is better ? The somewhat implicit contract of new is that it'll only instantiate some object. Here we do some serious work, maybe it'd be better to switch the name over ?

**Comment by ujh** [comment]
That is true, of course!

**Pull request merged**
