### PR TITLE
reg_genmove command

### LINKED ISSUE #285: Implement the reg_genmove GTP command
See https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

### PR DESCRIPTION
**Pull request by ujh**
Simulates a genmove but doesn't play the resulting move. Respects the time settings but doesn't update the remaining time.

Closes #285

### CODE REVIEW

**Comment by iopq** [comment]
I'm still incredulous that we have a test for the actual output string that we have to modify every time we add or remove a command.

**Comment by ujh** [comment]
That is not ideal, but then this whole GTP parsing code is a bit of a hack as we duplicate the list of commands. Once for `list_commands` and `known_command` and once for the actual command (a big match expression). That's why I think that test is still useful. Otherwise it would be possible to implement `reg_genmove` in the match expression but it won't appear in `list_commands` and so external tools wouldn't know it's there.

**Comment by iopq** [comment]
I remember when I had solved this issue 😉

**Comment by ujh** [comment]
In a more dynamic language I would have switched to a hash for this long ago. Use the keys for `list_commands` and `known_command` and execute the functions stored as values for the actual commands. Then everything would be in one place. I'm sure this is possible in Rust as well, but I haven't had the time (or the inclination) to figure that out yet.

**Pull request merged**
