### PR TITLE
[Work in progress]: 3x3 pattern matcher

### PR DESCRIPTION
**Pull request by ujh**
This is the first step towards a 3x3 pattern matcher that we can use in the priors (and later on in the playouts). This code here does almost nothing (just return `0` matching patterns) and the test code is also still broken.

But I'd still like to have feedback on the setup. As I imagine that setting up the pattern matcher is somewhat expensive (it has to compute all the rotations and color changes) I put it into an `Arc` and just pass it on. I thought about putting it into the `Config` but that's not really where it belongs, I think.

Do you think that this is the right way to go? Or would you put the code somewhere else?

### CODE REVIEW

**Comment by ujh** [comment]
Now with working tests. :)

**Comment by ujh** [comment]
As there were no objections I continue with this then. :grin:

**Comment by iopq** [comment]
Shouldn't it return a vector of moves instead of count of patterns?

**Comment by ujh** [comment]
I'm not in front of the code but I think my idea was that this happens in the leaf expansion so it's always called for just one move and checks if any patterns match.

**Comment by ujh** [comment]
But then I'm open to solutions that are more efficient that what I can come up with @iopq. How would you build the matcher for 3x3 patterns to be used for both the priors and the playouts?

**Comment by iopq** [comment]
It should just generate a list of suggestions and then from that list it should yield some moves that are 3x3 patterns. If the list is empty, a random legal move can be chosen.

**Comment by ujh** [comment]
I'll close this for now and open a new pull requests once I have something working.

**Pull request closed without merging**
