### PR TITLE
Atari check

### PR DESCRIPTION
**Pull request by iopq**
fix atari without doing the full ladder check in playouts

### CODE REVIEW

**Comment by iopq** [comment]
let me run this version on CGOS and see how it goes

**Comment by ujh** [comment]
So this is mutually exclusive to the ladder check then? Or do both need to be turned on for this to work? This getting confusing!

BTW, I'm currently testing the ladder check and it's really good. It's won 15 of 19 games with my usual setup (around 75-80% wins) which is quite an improvement from the 65% wins without it. We'll know more tomorrow when all 100 games were played.

**Comment by ujh** [comment]
If I understand this code right, you are trying to do a similar thing to the ladder reading but with less resources? Maybe that's not even needed right now. But if it's as good as the current version, then by all means let's use this one.

**Comment by iopq** [comment]
There are two expensive components:
1. finding groups in atari
2. finding out if that group can escape a ladder

I split those expensive parts into two:
1. You can try to save groups in atari
2. You can also check for ladders before you extend out

in my testing it's not as good on 9x9, but I  want to run it on CGOS to verify if the extra speed is worth it on 13x13

**Comment by ujh** [comment]
I see. I'd like to give it a try, too. So I just run it with `-use-atari-check-in-playouts`, right?

**Comment by iopq** [comment]
I put it as the default, because it's REQUIRED for the ladder option to make sense (if we don't fix atari we don't even check if anything is in ladder anyway), so it being false and ladder being true wouldn't do anything

**Comment by ujh** [comment]
Ah, I see. I'll run it without any additional command line options then.

**Comment by ujh** [comment]
If this works out then we should probably exit with an error if the Atari check is turned off when the ladder check is turned on.

**Comment by ujh** [comment]
I did some benchmarks and this version won 9/100 games on 13x13 with a time limit of 10 minutes against GnuGo (level 0). The current master with the ladder check turned on won 10/100. So both versions seem to be the same. I'm still waiting for the results with no checks at all.

**Comment by iopq** [comment]
CGOS is also inconclusive. The rank is virtually the same between the two versions. Maybe something like Michi (common short ladders) can be done.

**Comment by ujh** [comment]
I'm still waiting on the results when running it without either of the checks. We'll know more tomorrow.

**Comment by ujh** [comment]
I'm not sure if we will get much out of fiddling around with this at this point. Implementing something like 3x3 patterns (the original MoGo ones or the ones from Michi) for both the tree and the playouts will probably be much more valuable as will be implementing RAVE.

But obviously, if you have fun by all means give it a try. :grin:

**Comment by ujh** [comment]
GnuGo keeps crashing for some reason right now so I can't check how the bot performs without either of these checks. But it seems that it's slightly weaker.

I will just merge it like this and if that's OK with you I'll turn the ladder reading on by default in my branch where I'm refactoring the command line stuff.

**Pull request merged**
