### PR TITLE
Fixed a bug where the computation of win ratio would be 100% for new pass move

### PR DESCRIPTION
**Pull request by TisButMe**
This allows the MC Engine to actually play.

I've also bumped up the number of playouts/move to 1000 to reflect our gain in speed. On my machine, this give a playable 9x9, with some okayish moves generated (captures seen, etc...).

### CODE REVIEW

**Comment by ujh** [comment]
What exactly was the problem? Was it that `legal_moves()` contains `Pass` and that gets a wrong win ratio?

**Comment by ujh** [comment]
So what I'm actually asking is, where's the test for the bug? :trollface:

**Comment by TisButMe** [comment]
Good point.

**Comment by ujh** [comment]
I must admit that this is easier to say than to actually do it. I should be more vigilant with my pull requests, too.

**Comment by TisButMe** [comment]
There we go

**Comment by TisButMe** [comment]
It had nothing to do with Pass or not, just that with MoveStats.plays == 0, you have a float division by 0, which returns NaN, which screwed up the comparisons to a better move. This, in turn, caused the Pass move to always be chosen, as it had NaN% win ratio.

**Comment by TisButMe** [comment]
Btw, I though about fixing this by changing MoveStats so that new generates a MoveStat object with 1 play, but this means reducing a bit the differences between moves, and as we currently have very little playouts, I thought it might be a problem atm.

**Comment by ujh** [comment]
I still don't understand how we managed to have 0 plays at all. I mean, don't we iterate through all possible moves and run 1000 playouts? We should then have 1000 plays per possible move, right?

Also, setting play to 1 is probably the better fix.

**Comment by TisButMe** [comment]
That's not where this is happening.
After the playouts, where iterate through the generated stats to find the best move. During the iteration, we compare against the previously best move to elect the new best one. The problem lies in the initialization of the iteration, the first "best move" had its MoveStats created by MoveStats::new(), which generates a MoveStats with a win_ratio() of NaN, which apparently is >n for n in [0, 1].

**Comment by ujh** [comment]
Ah, now I understand!

**Pull request merged**
