### PR TITLE
UCT engine (WIP)

### PR DESCRIPTION
**Pull request by ujh**
I've started working on the UCT engine. There are currently not tests for *anything* and it doesn't even compile due to some mutability errors. But I thought that it could be interesting for you guys (@TisButMe & @iopq) to see where I'm at.

Before merging this I still want to do the following things:

1. Make it compile (duh!)
1. Write tests for at least the `Node` struct
1. Make it multi threaded

### CODE REVIEW

**Comment by ujh** [comment]
I've written a minimal example of my problem and posted it on stackoverflow: http://stackoverflow.com/questions/29296038/implementing-a-mutable-tree-structure Let's see if we can get this fixed soon.

**Comment by ujh** [comment]
It "works" now. Only the tests are broken. But I'm pretty sure there are bugs in the implementation as it's quite slow and consumes 4GB of RAM within 7 seconds. :grin:

**Comment by ujh** [comment]
One question though: The way the code is written it does put everything on the stack. Correct? Is this how I'm supposed to handle such (potentially) big amounts of memory? Or should I use boxes to put it on the heap?

**Comment by ujh** [comment]
A reminder to myself: I probably don't need to store the `Game` in the nodes. Storing the `Move` should be enough. I just need to modify `Playout` to take a list of moves to play in the beginning instead of just one. But first let's fix all the bugs. :)

**Comment by iopq** [comment]
The way that game.rs is written is really inefficient with cloning for every move.

You don't need to clone to CHECK if a move violates superko. But we currently do.

**Comment by ujh** [comment]
Well, but then you need to implement undo. To check super ko you actually need to play the move.

**Comment by ujh** [comment]
But you're right, if I want to do it correctly when I remove the `Game` from the `Node` then I need to have a way to check for super ko violations without playing a move. Well, at least the results would be more "correct" that way.

**Comment by ujh** [comment]
But I see what you're getting at. It's a bit out of scope of the first version here, I guess.

**Comment by ujh** [comment]
I've added a feature for it. https://trello.com/c/VzQnfGuU

**Comment by iopq** [comment]
I tried to make the UCT engine play a 19x19 board position, but it just went pass-pass and the game "ended". Why did that happen?

**Comment by ujh** [comment]
That's either because it played so few playouts (you can check in the GTP console of GoGui if you run it with `-l`) as the pass move is included in the list of moves it selects from or because of a bug in the UCT formula that produces `NaN`.

In all honesty it doesn't really make sense to try it at this point as it's probably still full of bugs and so, so slow.

**Comment by iopq** [comment]
In my pull request I only allow it to pass when it runs out of moves.

**Comment by ujh** [comment]
I wonder which tactic is better. I mean, at some point passing might be better or at least nice to the opponent. But we're probably not there, yet.

**Comment by ujh** [comment]
Much better now. I don't store any board state in the tree anymore. I just accumulate the moves during descent and just play them to generate the correct `Board` for the leaf. This is about 65% of the speed of raw playouts (on 19x19).

**Comment by ujh** [comment]
I'm done for today. The last commit is a multithreaded UCT implementation. But it's a bit too complex for me to say that it's bug free. I'll have to start testing stuff, but I wanted to throw this out here anyway.

**Comment by iopq** [comment]
Cargo bench doesn't work

**Comment by ujh** [comment]
I've updated the code to correctly calculate the wins, and what do you know it beats GnuGo level 0 on 9x9. :tada: Something is still wrong with the `wins` count on the root though.

**Comment by ujh** [comment]
I'll merge it like that for now. Further bug fixes can the go directly into master.

**Pull request merged**
