### PR TITLE
Set number of threads using a command line switch

### PR DESCRIPTION
**Pull request by ujh**
Setting the number of threads to use is machine dependent and setting it via the command line is just easier.

### CODE REVIEW

**Comment by iopq** [comment]
Disagree. You should have a permanent setting for each machine so you don't have to keep setting it every time.

**Comment by ujh** [comment]
But is there really one permanent setting per machine? And where would that be configured? For example I want to maybe run with all 36 cores when in a KGS tournament, but I want to use only 8 cores for the benchmarks so that I can run multiple copies per machine, etc.

Passing that in via a command line option seems simpler to me than having to write a configuration file in a script, passing it along to the executable, and then deleting it again afterwards.

**Comment by ujh** [comment]
_(Waiting for your response @iopq)_

**Comment by iopq** [comment]
I usually do 4 threads because I have 4 cores and I have hyperthreading disabled. Why can't it be done from both?

**Comment by ujh** [comment]
Yes, you're right. We could allow both. What should take precedence do you think? The command line option of the config file?

**Comment by iopq** [comment]
I think command line should take precedence because it's more of a pain to change the config file.

**Comment by ujh** [comment]
I've been thinking about it and how about aborting (with an appropriate error message of course) if the thread count is configured both in the config file and on the command line? That way you can always be sure where this is set. I can already see myself spending hours trying to figure out why a benchmark is so bad only to figure out that the thread count was set to something else than I expected.

**Comment by iopq** [comment]
Oakfoam has a parameters command where you can set the thread count at runtime.

```
param general
= [list/playout/1-ply/uct] move_policy uct
[bool] book_use 1
[string] thread_count 1
[string] memory_usage_max 2048
[string] playouts_per_move 10000
[string] playouts_per_move_max 1000000
[string] playouts_per_move_min 1000
[bool] pondering_enabled 0
[string] pondering_playouts_max 1000000

param general thread_count 4
= 
```

**Comment by ujh** [comment]
That sounds cool, would it be OK for you to not do this now, however?

**Comment by iopq** [comment]
I think the more temporary settings should take precedence.

run-time > command-line > config > default in order

So if you have a command-line switch set and you had a run-time command, it would be very unpleasant if you had to reload the executable just because you already had the switch from the command-line. What would be the point of run-time options if you can't change them anyway?

Similarly, if you have a settings file, what would be the point of a command line switch if you can't use it anyway, since once you have it in a settings file you have to change the settings file?

**Comment by ujh** [comment]
That is true. OK, so I'll make it so that the command line switch overrides the value from the config file. 

Thanks for the input!

**Pull request merged**
