### PR TITLE
slight cleanup

### PR DESCRIPTION
**Pull request by iopq**
minor cleanup improves performance for some reason

### CODE REVIEW

**Comment by ujh** [comment]
But it's also wrong. Now the engine might return a a super ko violation which it didn't do previously. But really, this code is quite buggy still and will change quite a lot and I think you're waisting your time working on it.

**Comment by iopq** [comment]
I didn't change what your code did, I just eliminated extra bools.

**Comment by ujh** [comment]
You did! I passed in a `Game` into the root which check for super ko violations. Now it uses `Board` which doesn't check for super ko violations.

**Comment by ujh** [comment]
It's however not clear if this will be the final design. Maybe I'll remove the root related code from `Node` and move into a separate struct.

**Comment by iopq** [comment]
You're right, I overlooked it. Most of the time game.something is identical to board.something! Even so, that superko check is free (just a lookup) if we don't copy the board.

But the way that Vec<T> is used to carry things between functions is a huge performance concern. Maybe we can do better by using iterators directly.

**Comment by ujh** [comment]
Yes, the recursive calls aren't that nice. But again, I'd like to get this tested first and then we can get rid of the recursive calls. Also, because there's no tail call optimisation IIRC.

**Pull request merged**
