### PR TITLE
Reuse subtree in uct search

### PR DESCRIPTION
**Pull request by ujh**
This is a preview of the new code to reuse the subtree of the UCT search for the next search. It seems to work, but it exhibits a somewhat weird behaviour. Unlike before the win ratio of the best move and the average drift apart. There's probably still a bug in there as a win ratio of 0% for the best move and some positive value for the average is somewhat unlikely. ;)

### CODE REVIEW

**Comment by ujh** [comment]
As I had suspected, there was still a bug in there. I hadn't reset the color of the root node.

**Comment by ujh** [comment]
It looks good now, I think. But I'll have to see how it compares to the previous version before merging, I think.

**Comment by iopq** [comment]
Can you log!() how much of the tree you reuse like Fuego does? Like 82% of previous tree reused or something.

**Comment by ujh** [comment]
That sounds interesting. Do you happen to know how Fuego computes this percentage? Is it the number of nodes? Or does it take the playouts that went through the nodes into account?

**Comment by iopq** [comment]
It prints `GoUctPlayer: Reusing 971128 nodes (89%)`

**Comment by ujh** [comment]
Thanks. That should be easy to implement by storing the descendant count in each node. Then we also know how big the tree for the first time.

**Comment by ujh** [comment]
The tests are done and this improves the wins against GnuGo level 0 on 9x9 (5m sudden death) from 35% to 40%. Not huge, but (barely) above the error margin, so I guess it can be merged.

**Pull request merged**
