### PR TITLE
There's a little bit of confusion about my functions

### PR DESCRIPTION
**Pull request by iopq**
`save_group` saves a group with the player to act, while not being able to `save_group` means it is as good as dead

if you call it with the other player to act, it doesn't work, because there's a way to save this group, but if it's the other player to act he will just capture it, because it's in atari, so that's why you need to call `capture_ladder`

additionally, you have to make the move first because it reads out the entire ladder so it has to have all the stones in place

don't merge yet, the code is not stable

### CODE REVIEW

**Comment by iopq** [comment]
in general, because of the clone requirement I want to actually rewrite the priors code to first look at our own groups currently in danger and opponent groups in danger instead of testing every move for whether it puts someone in danger or leaves a group vulnerable

**Comment by ujh** [comment]
Sure, go ahead. Do you want to do it in this pull request?

**Comment by ujh** [comment]
Also, keep in mind that we probably want to use this code in the playouts, too. So maybe `Node` isn't the correct place for those functions.

**Comment by ujh** [comment]
So what you're saying is that you want to check if we put our own group into danger and then *not* check for capturing an opponent group?

**Pull request merged**
