### PR TITLE
Resigning a game

### PR DESCRIPTION
**Pull request by ujh**
Resigning when you know with certainty that you've lost is just polite. So now we support resigning in `McEngine` when all playouts lead to a loss.

### CODE REVIEW

**Comment by TisButMe** [comment]
The code looks fine, but do we have enough playouts/move now that the risk of early resigning because of random bad luck in the playouts is ok ? We could recover (for some definition of recover) after a pass in a losing game, we can't after a resign.

**Comment by ujh** [comment]
I'm not too worried about this, as what the `McEngine` implements is barely better than random play anyway. Once we're implementing [UCT](http://senseis.xmp.net/?UCT) we need to be more careful with that kind of stuff, but for now I wouldn't worry too much about it.

**Comment by ujh** [comment]
But if you prefer, I can of course take that out again, so that we don't resign in `McEnigne`.

**Comment by TisButMe** [comment]
No, I agree with the resign move. Even if the engine sometimes resigns for no reason, the actual solution will be to have more playouts (or selection of playouts), not pretending you didn't see that 100% loss result.

I just wanted to raise the issue to see if you had any opinion on it. Also, I've played some games against the engine where it'll pass on one move (which I assume is a resign move in disguise), but then will happily continue playing.

**Comment by ujh** [comment]
OK, so I'll merge it like this and we can see what to make of it. :)

**Pull request merged**
