### PR TITLE
Ownership analyze command

### PR DESCRIPTION
**Pull request by ujh**
This pull requests adds the following two GTP commands:

1. `gogui-analyze_commands`
1. `imrscl-ownership`

The first one is used by GoGui to query the supported [analyze commands](http://gogui.sourceforge.net/doc/analyze.html), which right now for Iomrascálaí is just `imrscl-ownership`. And that one shows an overlay on the board of the "safe" points, i.e. the points (empty and occupied) that were counted as territory for one color in more than 90% of the playouts run for the last `genmove`.

I've also added the same output as [GoGui live graphics](http://gogui.sourceforge.net/doc/live-gfx.html) as the analyze commands can only be used when playing directly in Gogui. Once you switch to `gogui-twogtp` (i.e. observing a game between two engines in GoGui) the analyze commands can't be used anymore.

territory

Implements #225 & #240.

### CODE REVIEW

**Comment by iopq** [comment]
Wow, really cool.

**Comment by ujh** [comment]
It wasn't even that much work to implement. And now we can use it to implement Chinese scoring (#214) and a smarter way to stop playing (#238).

**Comment by ujh** [comment]
BTW, I kicked out your `strenum` crate as I had to support GTP commands with hyphens. And the easiest way to support that was to switch back to using strings.

**Comment by iopq** [comment]
Yeah, I like the way that you did it. I think it can be merged as is as long as it works (I didn't try it myself, yet)

I think the parser can be actually made better (more generic vis-a-vis argument number), but I could make that change after this is merged

**Comment by ujh** [comment]
Yes, the parser still isn't ideal. I would have preferred to have it even more dynamic and just have a `HashMap` with the command names as arguments and closures as keys that then get executed. That way wouldn't have to duplicate the list of commands to support `list_commands`. But as the closures need to have mutable access to the controller that wasn't possible.

But yes, the GTP parser and related parts haven't been touched for a long, long time and aren't that well thought out.

**Pull request merged**
