### PR TITLE
Playouts in the middle of a real eye

### PR DESCRIPTION
**Pull request by iopq**
This version performs better than either the master or the previous incarnation. Test it to see if that's true on your machine as well.

It also makes this playout type a config option if you want to turn it off.

### CODE REVIEW

**Comment by iopq** [comment]
I got 13.5% +/- 4.7% win rate vs. Gnugo with this version

**Comment by ujh** [comment]
Awesome. Sorry for the delay, I just got around to starting the benchmark. It will be a while. ;)

**Comment by iopq** [comment]
I'll run it on CGOS and see how it does.

**Comment by iopq** [comment]
So far, this is the strongest version of Iomrascalai on CGOS ever.

**Comment by ujh** [comment]
13.5% +/- 2.4% is what I get on 13x13. :+1:

**Pull request merged**
