### PR TITLE
Make everything configurable

### PR DESCRIPTION
**Pull request by ujh**
To make everything configurable I've replaced all the command line switches with a config file. It's not ideal as the config file needs to contain all options.

### CODE REVIEW

**Comment by iopq** [comment]
I'm not a fan of configuration files in git. It's easy to accidentally commit them. If they are git ignored, the program needs to work without them, otherwise it doesn't work out of the box.

**Comment by ujh** [comment]
I'm not sure I like this solution either. Mostly because the config file needs to contain all variables right now. 

To your specific point @iopq. It works without a config file due to the use of `include_str!`.

**Comment by iopq** [comment]
It should just override the current defaults one by one as the value is found. It shouldn't just crash if you're missing one. I see how it works with `include_str!` now. So that seems fine, as long as the config file doesn't have to have all the values when one is found.

**Comment by ujh** [comment]
I've been thinking about this and I believe it won't be too hard to allow a config file that doesn't contain all values.

As for storing the default configuration in `defaults.toml`. My idea there was that with a setup like this it's totally obvious if an option can't be set via an external config file as all other values would be taken from `defaults.toml` but that particular one wouldn't. I'm not sure if it's worth the extra hassle to make sure everything is always configurable.

**Comment by ujh** [comment]
OK, so now you can pass a config file that doesn't contain all entries. The missing ones are taken from `defaults.toml`. The error messages are also somewhat nicer now as I don't use `unwrap()` anymore.

**Comment by iopq** [comment]
I haven't tested it, but from what I can see it's good to go.

**Pull request merged**
