### PR TITLE
This PR adds benchmarks for all time-sensitive methods.

### PR DESCRIPTION
**Pull request by TisButMe**
If we are to improve perfs, we need good ways of measuring them. This PR is a start on that route.

This removes the old way of manually benchmarking, along with the dependency on time which is not needed anymore.

### CODE REVIEW

**Comment by ujh** [comment]
Crap, I just realised that this is not nice. How are we going to profile the code without the benchmark mode? I was running the executable inside the profile with `-m pps` and got great results to look at.

**Comment by ujh** [comment]
Never mind :flushed:

**Comment by TisButMe** [comment]
I suspect you've discovered it by now, but you can run cargo bench --name name_of_benchmark to only run one benchmark. Then you can profile that I suppose :)

As to why to reported pps is higher, Bencher is made especially to reduce as much as possible to overhead, so I think the difference might have been in overhead ?

**Comment by ujh** [comment]
That's more or less what I'm doing. `cargo bench` isn't very suitable for profiling though, as it uses an optimized build. So I instead run `cargo test` and then use that executable with `--bench "playout::test::bench_9x9_playout_speed"`.

**Comment by TisButMe** [comment]
Oh, that's a better idea. Why is the optimized build a problem though ? If the compiler is getting rid of something, we should know while profiling, or we might optimizing stuff the the compiler already optimizes ?

**Comment by ujh** [comment]
I tried it and it's just harder to see what code is called with all the optimisations going on. I will try it this way and as I'll run `cargo bench` to see if there was a speed up I'll find out if there's a mismatch and if I need to switch to the optimized build.

**Comment by TisButMe** [comment]
Oh, ok :)

**Pull request merged**
