### PR TITLE
Weighted playouts

### PR DESCRIPTION
**Pull request by ujh**
Add a tiny incentive for winning by a bigger margin. Will be optimized using CLOP, too.

### CODE REVIEW

**Comment by iopq** [comment]
For what purpose? It's usually weaker like that

**Comment by ujh** [comment]
According to Petr Baudis' thesis a small weight produced slightly better looking games. I'm currently running CLOP on this anyway so maybe it will find that 0.0 is the best value for that variable.

**Comment by iopq** [comment]
What did CLOP say?

**Comment by ujh** [comment]
I'll open a new pull request once the results are in. It will take a while as CLOP needs to run hundreds of games.

**Pull request merged**
