### PR TITLE
Add the caffe crate

### PR DESCRIPTION
**Pull request by ujh**
Let's try using caffe.rs again. I updated to the latest rust-bindgen crate. It unfortunately generates invalid Rust code and I've already opened an issue for it: https://github.com/crabtw/rust-bindgen/issues/359. If worst comes to worst I can just copy the generated code into the crate itself.

I've also tried statically linking it and that seems to work as well. Next is actually trying it out and getting it to compile on Travis and AppVeyor.

### CODE REVIEW

**Comment by iopq** [comment]
Is it working now?

**Comment by ujh** [comment]
Caffe is integrated, but obviously it only works with the files in the correct location on my machine. ;) I will have to fix that next. And then I'm also not sure if I picked the correct blob as the output. I would have thought that "softmax" would be correct but somehow that doesn't work.

It is also slow as hell when I run this on each node expansion. I'm down to 6pps with this code. Even on 9x9.

**Comment by ujh** [comment]
I also realised that the NN I'm using here is just useful for 19x19.

**Comment by ujh** [comment]
You'll now have to use my caffe repo and I added a method to the ffi.hpp/cpp module.

**Comment by ujh** [comment]
Still horribly slow even though it now only runs on nodes of depth 1.

**Comment by ujh** [comment]
It (sort of) works but it's weaker than `master` on 19x19. I think I'll leave it for now and do easier things like large patterns (can be stolen from michi) or criticality. Once that's done I may come back to it and do a proper implementation and probably train the NN myself.

**Pull request closed without merging**
